### ISSUE TITLE
@tag @info

### ISSUE THREAD

**Issue by malys** [daolf/grunt-gallery#1]
Ces balises ne sont pas standards voir http://usejsdoc.org/

@info pourrait être remplacé par @description

@tag -> @see mais pas convaincu 

Du coup, on reste standard :)

**Comment by daolf** [comment]
Bonne idée pour le @info en @description c'est effectivement plus pertinent.

Les tags n'étant pas inclus dans la javadoc standard je pense garder le @tags. En effet en utilisant @see si des gens génère de la javadoc par dessus la galerie cela pourrait créer des incohérences.

Ca arrive dans la 1.0.0
